### ISSUE TITLE
Add structured_output method support

### ISSUE THREAD

**Issue by Data-drone** [langchain-ai/langchain-databricks#19]
The latest method recommended for generating structured responses is the method outlined here: 
https://python.langchain.com/docs/how_to/structured_output/#the-with_structured_output-method

it looks like ChatDatabricks currently doesn't support with_structured_output method

**Comment by B-Step62** [comment]
@Data-drone Sorry for the late response, we have added the support for structured output in the above PR and it will be released in the next version soon.

**Comment by B-Step62** [comment]
`langchain-databricks` 0.1.1 is released and now structured output is supported in `ChatDatabricks`.
